# Generated by Django 4.2.16 on 2025-12-30 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
        ('fleet', '0002_auto_20211109_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='shifts', to='fleet.bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='shifts', to='fleet.driver')),
            ],
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Scheduled time at the designated place for the related bus shift')),
                ('bus_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='fleet.busshift')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stops', to='geography.place')),
            ],
        ),
        migrations.AddConstraint(
            model_name='busstop',
            constraint=models.UniqueConstraint(fields=('place', 'time', 'bus_shift'), name='unique_bus_stop_combination'),
        ),
    ]
