# Generated by Django 4.2.16 on 2026-01-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_busshift_busstop_busstop_unique_bus_stop_combination'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busstop',
            options={'ordering': ['time']},
        ),
        migrations.AlterField(
            model_name='busstop',
            name='time',
            field=models.DateTimeField(verbose_name='Scheduled time of arrival at the stop'),
        ),
    ]
